"""add post category stable

Revision ID: 145903a6328c
Revises: 20260724_01
Create Date: 2026-07-28 12:28:34.927843
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


revision: str = '145903a6328c'
down_revision: str | None = '20260724_01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 的 DDL 不能完整事务回滚：若后续新增非空列失败，categories 表仍会
    # 留在数据库中。仅在表不存在时创建，使修复历史数据后的重试可以继续执行。
    if not inspect(op.get_bind()).has_table('categories'):
        op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('slug', sa.String(length=50), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
        )
    # SQLite 不支持直接 ALTER TABLE ADD CONSTRAINT。batch 模式会重建 posts 表，
    # PostgreSQL 上也能生成等价结构，因此两种开发环境共用同一条迁移路径。
    with op.batch_alter_table('posts') as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_index(op.f('ix_posts_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_posts_category_id_categories',
            'categories',
            ['category_id'],
            ['id'],
            ondelete='RESTRICT',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_constraint('fk_posts_category_id_categories', type_='foreignkey')
        batch_op.drop_index(op.f('ix_posts_category_id'))
        batch_op.drop_column('category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
